#pre-commit install
#pre-commit run --all-files

repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Assure-toi de spécifier la version correcte
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length', '79']
        files: ^_resources/  # Limite l'exécution aux fichiers du répertoire _resources

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Version d'isort
    hooks:
      - id: isort
        args: ['--profile', 'black']  # Utilise le style d'importations de black
        files: ^_resources/  # Limite l'exécution aux fichiers du répertoire _resources

# repos:
#   - repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.812  # Version de mypy
#     hooks:
#       - id: mypy
#         files: ^_resources/  # Limite l'exécution aux fichiers du répertoire _resources


  # - repo: https://github.com/pycqa/flake8
  #   rev: v5.0.4  # Version de flake8
  #   hooks:
  #     - id: flake8
  #       args: ['--max-line-length=79']
  #       files: ^_resources/  # Limite l'exécution aux fichiers du répertoire _resources


  # - repo: https://github.com/pre-commit/mirrors-flake8
  #   rev: v5.0.4
  #   hooks:
  #     - id: flake8
  #       args: ['--max-line-length=79']
  #       files: ^_resources/  # Limite l'exécution aux fichiers du répertoire _resources

# repos:
#   - repo: local
#     hooks:
#       - id: black
#         name: black
#         entry: ./hooks/black
#         language: python
